version: '3.8'

services:
  cohort-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cohort_service
    container_name: cohort_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - cohort

  webserver:
    image: nginx:alpine
    container_name: cohort_webserver
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cohort

  db:
    image: mysql:5.7
    container_name: dblr-cohorts
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dblr-cohorts
      MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_USER: admin
    ports:
      - "3307:3306"
    networks:
      - cohort

networks:
  cohort:
    driver: bridge
